# Ensure user home directories exist under /var/home across OSTree upgrades
q  /var/home      0755  root  root  -
q  /var/roothome  0700  root  root  -

# Writable /usr/local via /var/usrlocal (OSTree-compatible)
d  /var/usrlocal          0755  root  root  -
d  /var/usrlocal/bin      0755  root  root  -
d  /var/usrlocal/etc      0755  root  root  -
d  /var/usrlocal/include  0755  root  root  -
d  /var/usrlocal/lib      0755  root  root  -
d  /var/usrlocal/share    0755  root  root  -
d  /var/usrlocal/sbin     0755  root  root  -
L+ /var/usrlocal/bin/alga    -  -  -  -  /usr/lib/ark/alga-wrapper
L+ /var/usrlocal/bin/pacman  -  -  -  -  /usr/lib/ark/pacman
