#!/bin/bash
if ! podman container exists archlinux 2>/dev/null; then
    distrobox create --image ghcr.io/archlinux/archlinux:latest --name archlinux --no-entry --yes >/dev/null 2>&1
fi
exec distrobox enter archlinux
