name: Build ark Payload

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  build-payload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        variant: [ark, ark-nvidia, ark-zen, ark-zen-nvidia, ark-lts, ark-lts-nvidia, ark-hardened, ark-hardened-nvidia]
    steps:
      - uses: actions/checkout@v6
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y podman wget
      - name: Download AUR packages
        run: |
          mkdir -p aur-packages
          cd aur-packages
          curl -sL https://github.com/zamkara/ark-aur/releases/expanded_assets/latest | grep -o 'href="[^"]*\.pkg\.tar\.zst"' | cut -d'"' -f2 | sed 's|^|https://github.com|' | wget -qi - || true
          cd ..
      - name: Download Alga Package
        run: |
          cd aur-packages
          curl -sL https://github.com/zamkara/alga/releases/expanded_assets/latest | grep -o 'href="[^"]*\.pkg\.tar\.zst"' | cut -d'"' -f2 | sed 's|^|https://github.com|' | wget -qi - || true
          cd ..
      - name: Cache Pacman Payload
        uses: actions/cache@v4
        with:
          path: pacman-cache/
          key: ${{ runner.os }}-pacman-payload-${{ matrix.variant }}-${{ hashFiles('Containerfile') }}
          restore-keys: |
            ${{ runner.os }}-pacman-payload-${{ matrix.variant }}-
            ${{ runner.os }}-pacman-payload-
      - name: Prepare Cache Dir
        run: mkdir -p pacman-cache
      - name: Build custom ark image with bootupd
        run: |
          sudo podman build -v $(pwd)/pacman-cache:/var/cache/pacman/pkg --squash-all --build-arg VARIANT=${{ matrix.variant }} -t ghcr.io/${{ github.repository }}:${{ matrix.variant }} -f Containerfile .
          sudo chown -R $USER:$USER pacman-cache/
      - name: Log in to the Container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push payload image to GHCR
        run: sudo podman push ghcr.io/${{ github.repository }}:${{ matrix.variant }}
